version: "3"
services:
  activemq:
    image: rmohr/activemq:5.14.5
    container_name: activemq
    restart: always
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ACTIVEMQ_CONFIG_MINMEMORY: 512
      ACTIVEMQ_CONFIG_MAXMEMORY: 1024
    healthcheck:
      test: curl -u admin:admin -s http://activemq.service:8161/admin
      interval: 5s
      retries: 20
    networks:
      app_net:
        #ipv4_address: 172.16.238.3
        aliases:
          - activemq.service

  eureka:
    build: ../eureka_server
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      app_net:
        #ipv4_address: 172.16.238.2
        aliases:
          - eureka.service

  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - mariadb-volume:/var/lib/mysql
    healthcheck:
      test: mysql --user=root --password=mysql -h mariadb.service
      interval: 5s
      retries: 20
    networks:
      app_net:
        #ipv4_address: 172.16.238.4
        aliases:
          - mariadb.service

  cassandra:
    image: cassandra
    container_name: cassandra
    ports:
      - "9042:9042"
    healthcheck:
      test: cqlsh ping -h cassandra.service
      interval: 5s
      retries: 20
    networks:
      app_net:
        #ipv4_address: 172.16.238.5
        aliases:
          - cassandra.service
    volumes:
      - cassandra-volume:/var/lib/cassandra

volumes:
  cassandra-volume:
  mariadb-volume:

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
